on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        goversion: "1.17"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.os }}
        goarch: ${{ matrix.arch }}

